### ISSUE TITLE
Healthcheck fails when Connect throws error

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/sqlds#44]
After migrating to the managed data source, `CheckHealth` doesn't throw an actual health check error if the `Connect` throws an error. If the `Connect` method throws error, healthcheck failed with the  generic error message **Plugin health check failed**

![image](https://user-images.githubusercontent.com/153843/133239766-b9981a33-a57b-484b-9636-106dbfcee42c.png)

**Comment by shelldandy** [comment]
Seems like this has been fixed for a while in https://github.com/grafana/grafana-plugin-sdk-go/pull/389
